<!doctype html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Instalação!</title>
  </head>
  <body>
    
    <div class="container">
      <div class="py-5 text-center">
        <img class="d-block mx-auto mb-4" src="./img/prepara-cursos-logo.png" alt="Prepara cursos logo">
        <h2>Instalando, Passo a Passo</h2>
        <p class="lead">Aqui está a versão rápida das instruções, para aqueles que já estão confortáveis com a realização de tais instalações.</p>
        <div class="text-left">
          <ul>
            <li>Baixe e descompacte o pacote do Quiz, se você ainda não o fez.</li>
            <li>Crie um banco de dados para o Quiz no seu servidor web, no MySQL com um usuário com todos os privilégios de acesso e modificação.</li>
            <li>Execute o script de instalação do Quiz, acessando [URL]/install.php no seu navegador.</li>
            <li>É isso aí! O Quiz agora deve estar instalado!</li>
          </ul>
        </div>
      </div>


      <div class="row" id="app">
        <div class="col-md-12" v-if="sucesso">
          <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Instalação concluída com sucesso</h4>
            <p class="md-0">
              <a href="./home">Click aquí para voltar à tela principal</a>
            </p>
          </div>
        </div>
        <div class="col-md-12" v-if="error">
          <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">Atenção!</h4>
            <p class="mb-0">{{ error_log }}</p>
          </div>
        </div>
        <div class="col-md-4 order-md-2 mb-4">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Etapas</span>
            <span class="badge badge-secondary badge-pill">{{ indexConfig }}</span>
          </h4>
          <ul class="list-group mb-3">
            <li class="list-group-item d-flex justify-content-between" v-bind:class="{ 'bg-light': indexConfig == 1 }">
              <div>
                <h6 class="my-0">Configuração básica</h6>
                <small class="text-muted">Uma breve configuração sobre o servidor!</small>
              </div>
              <span class="text-muted">1</span>
            </li>
            <li class="list-group-item d-flex justify-content-between" v-bind:class="{ 'bg-light': indexConfig == 2 }">
              <div>
                <h6 class="my-0">Banco de dados</h6>
                <small class="text-muted">Criação do banco de dados</small>
              </div>
              <span class="text-muted">2</span>
            </li>
            <li class="list-group-item d-flex justify-content-between" v-bind:class="{ 'bg-light': indexConfig == 3 }">
              <div class="text-success">
                <h6 class="my-0">Informações legais</h6>
                <small>@ReinanHS | <a href="https://github.com/ReinanHS/Prepara-Curso-Mine-Quiz">GitHub</a></small>
              </div>
              <span class="text-success">Grátis</span>
            </li>
          </ul>

          <form class="card p-2">
            <div class="row">
              <div class="input-group col-3">
                <div class="input-group-append">
                  <button class="btn btn-success" @click.stop.prevent="nextConfig()" v-if="!sucesso">{{ etapa }}</button>
                </div>
              </div>
              <div class="input-group col-3">
                <div class="input-group-append">
                  <button class="btn btn-primary" @click.stop.prevent="prevConfig()" v-if="indexConfig > 1">Voltar</button>
                </div>
              </div>
            </div>
          </form>
        </div>

        <div class="col-md-8 order-md-1">

          <config-1 v-if="indexConfig == 1"></config-1>
          <config-2 v-if="indexConfig == 2"></config-2>
          <config-3 v-if="indexConfig == 3"></config-3>

          <button class="btn btn-primary btn-lg btn-block" type="submit" @click.stop.prevent="nextConfig()" v-if="!sucesso">{{ etapa }} etapa</button>
        </div>
      </div>

      <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">&copy; 2017-2018 ReinanHS</p>
        <ul class="list-inline">
          <li class="list-inline-item"><a href="#">Privacidade</a></li>
          <li class="list-inline-item"><a href="#">Termos</a></li>
          <li class="list-inline-item"><a href="#">Suporte</a></li>
        </ul>
      </footer>
    </div>


    <template id="config1">
      <form class="needs-validation">
        <h4 class="mb-3">Configurações Básicas</h4>
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="url">Diretório raiz</label>
            <input type="text" class="form-control" id="url" placeholder="http://seu-domínio.com/minha-pasta/" value="http://localhost" required v-model="input_url">
            <div class="invalid-feedback">
              Valid url is required.
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="tipoData">Tipo do banco de dados</label>
            <select class="form-control" id="tipoData" v-model="input_tipo">
              <option value="mysql">Mysql</option>
              <option value="json">JSON</option>
            </select>
          </div>

          <!-- Admin -->
          <div class="col-md-6 mb-3">
            <label for="adminName">Admin ( Opcional )</label>
            <input type="text" class="form-control" id="adminName" placeholder="Qual é o nome do admin" value="Admin" v-model="input_admin">
            <div class="invalid-feedback">
              Valid url is required.
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="adminSenha">Senha ( Opcional )</label>
            <input type="password" class="form-control" id="adminSenha" placeholder="Qual é a senha?" v-model="input_senha">
            <div class="invalid-feedback">
              Valid url is required.
            </div>
          </div>
        </div>

        <hr class="mb-4">
      </form>
    </template>

    <template id="config2">
      <form class="needs-validation">
        <h4 class="mb-3">Informações do Mysql</h4>
        <div class="row">
          
          <div class="col-md-12">
            <label for="hostdb">Host</label>
            <input type="text" class="form-control" id="hostdb" placeholder="Qual é o host?" v-model="input_host">
          </div>

          <div class="col-md-6 mb-3">
            <label for="dbname">Banco De Dados</label>
            <input type="text" class="form-control" id="dbname" placeholder="Qual é o dbname?" v-model="input_dbname">
          </div>
          <div class="col-md-6 mb-3">
            <label for="podbrt">Porta</label>
            <input type="text" class="form-control" id="dbport" placeholder="Qual é a porta?" value="21">
          </div> 
          

          <div class="col-md-6 mb-3">
            <label for="dbuser">Usuário</label>
            <input type="text" class="form-control" id="dbuser" v-model="input_user" placeholder="Qual é o usuário?">
          </div>
          <div class="col-md-6 mb-3">
            <label for="dbSenha">Senha</label>
            <input type="password" class="form-control" id="dbSenha" placeholder="Qual é a senha?" v-model="input_senha">
          </div>        
  
        </div>

        <hr class="mb-4">
      </form>
    </template>

    <template id="config3">
      <form class="needs-validation">
        <h4 class="mb-3">Informações Gerais</h4>
        <div class="row">
          
          <div class="col-md-6">
            <div class="alert alert-primary" role="alert">
              Versão do PHP <?php echo phpversion(); ?>
            </div>
          </div>

          <div class="col-md-6">
            <div class="alert alert-success" role="alert">
              Versão do Vue.js 2.X
            </div>
          </div>

          <div class="col-md-6">
            <div class="alert alert-dark" role="alert">
              Versão do Jquery 3.3.1
            </div>
          </div>

          <div class="col-md-6">
            <div class="alert alert-info" role="alert">
              Versão do Bootstrap 4.1.3
            </div>
          </div>

          <p class="mb-3">Perfil comportamental é uma maneira de decifrar e decodificar os comportamentos que as pessoas possuem sob certos estímulos. Cada ser humano possui formas diferentes de agir e de se comportar diante das situações e é fundamental que todos saibam respeitar a individualidade das pessoas.</p>

        <hr class="mb-4">
      </form>
    </template>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <!-- Vuejs -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue-resource@1.5.1"></script>
    <script src="./js/install.js"></script>
  </body>
</html>