<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>System error</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.1/build/styles/default.min.css">
    <script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.1/build/highlight.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlightjs-line-numbers.js/2.8.0/highlightjs-line-numbers.min.js"></script>
    <style>
        #app {
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        .background {
            position: absolute;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
            background: linear-gradient(transparent, rgba(0, 0, 0, 0.5)), url("https://images.pexels.com/photos/4827/nature-forest-trees-fog.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260");
            background-size: cover;
            background-position: center;
        }

        .modalbox.success,
        .modalbox.error {
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
            transition: all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1);
            -webkit-border-radius: 2px;
            -moz-border-radius: 2px;
            border-radius: 2px;
            background: #fff;
            padding: 25px 25px 15px;
            text-align: center;
        }

        .modalbox.success.animate .icon,
        .modalbox.error.animate .icon {
            -webkit-animation: fall-in 0.75s;
            -moz-animation: fall-in 0.75s;
            -o-animation: fall-in 0.75s;
            animation: fall-in 0.75s;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
        }

        .modalbox.success h1,
        .modalbox.error h1 {
            font-family: 'Montserrat', sans-serif;
        }

        .modalbox.success p,
        .modalbox.error p {
            font-family: 'Open Sans', sans-serif;
        }

        .modalbox.success button,
        .modalbox.error button,
        .modalbox.success button:active,
        .modalbox.error button:active,
        .modalbox.success button:focus,
        .modalbox.error button:focus {
            -webkit-transition: all 0.1s ease-in-out;
            transition: all 0.1s ease-in-out;
            -webkit-border-radius: 30px;
            -moz-border-radius: 30px;
            border-radius: 30px;
            margin-top: 15px;
            width: 80%;
            background: transparent;
            color: #4caf50;
            border-color: #4caf50;
            outline: none;
        }

        .modalbox.success button:hover,
        .modalbox.error button:hover,
        .modalbox.success button:active:hover,
        .modalbox.error button:active:hover,
        .modalbox.success button:focus:hover,
        .modalbox.error button:focus:hover {
            color: #fff;
            background: #4caf50;
            border-color: transparent;
        }

        .modalbox.success .icon,
        .modalbox.error .icon {
            position: relative;
            margin: 0 auto;
            margin-top: -75px;
            background: #4caf50;
            height: 100px;
            width: 100px;
            border-radius: 50%;
        }

        .modalbox.success .icon span,
        .modalbox.error .icon span {
            position: absolute;
            font-size: 4em;
            color: #fff;
            text-align: center;
            padding-top: 20px;
        }

        .modalbox.error button,
        .modalbox.error button:active,
        .modalbox.error button:focus {
            color: #f44336;
            border-color: #f44336;
        }

        .modalbox.error button:hover,
        .modalbox.error button:active:hover,
        .modalbox.error button:focus:hover {
            color: #fff;
            background: #f44336;
        }

        .modalbox.error .icon {
            background: #f44336;
        }

        .modalbox.error .icon span {
            padding-top: 25px;
        }

        .center {
            float: none;
            margin-left: auto;
            margin-right: auto;
            /* stupid browser compat. smh */
        }

        .center .change {
            display: block;
            font-size: 10px;
            color: #ccc;
            margin-top: 10px;
        }

        @-webkit-keyframes fall-in {
            0% {
                -ms-transform: scale(3, 3);
                -webkit-transform: scale(3, 3);
                transform: scale(3, 3);
                opacity: 0;
            }

            50% {
                -ms-transform: scale(1, 1);
                -webkit-transform: scale(1, 1);
                transform: scale(1, 1);
                opacity: 1;
            }

            60% {
                -ms-transform: scale(1.1, 1.1);
                -webkit-transform: scale(1.1, 1.1);
                transform: scale(1.1, 1.1);
            }

            100% {
                -ms-transform: scale(1, 1);
                -webkit-transform: scale(1, 1);
                transform: scale(1, 1);
            }
        }

        @-moz-keyframes fall-in {
            0% {
                -ms-transform: scale(3, 3);
                -webkit-transform: scale(3, 3);
                transform: scale(3, 3);
                opacity: 0;
            }

            50% {
                -ms-transform: scale(1, 1);
                -webkit-transform: scale(1, 1);
                transform: scale(1, 1);
                opacity: 1;
            }

            60% {
                -ms-transform: scale(1.1, 1.1);
                -webkit-transform: scale(1.1, 1.1);
                transform: scale(1.1, 1.1);
            }

            100% {
                -ms-transform: scale(1, 1);
                -webkit-transform: scale(1, 1);
                transform: scale(1, 1);
            }
        }

        @-o-keyframes fall-in {
            0% {
                -ms-transform: scale(3, 3);
                -webkit-transform: scale(3, 3);
                transform: scale(3, 3);
                opacity: 0;
            }

            50% {
                -ms-transform: scale(1, 1);
                -webkit-transform: scale(1, 1);
                transform: scale(1, 1);
                opacity: 1;
            }

            60% {
                -ms-transform: scale(1.1, 1.1);
                -webkit-transform: scale(1.1, 1.1);
                transform: scale(1.1, 1.1);
            }

            100% {
                -ms-transform: scale(1, 1);
                -webkit-transform: scale(1, 1);
                transform: scale(1, 1);
            }
        }

        @-webkit-keyframes plunge {
            0% {
                margin-top: -100%;
            }

            100% {
                margin-top: 25%;
            }
        }

        @-moz-keyframes plunge {
            0% {
                margin-top: -100%;
            }

            100% {
                margin-top: 25%;
            }
        }

        @-o-keyframes plunge {
            0% {
                margin-top: -100%;
            }

            100% {
                margin-top: 25%;
            }
        }

        @-moz-keyframes fall-in {
            0% {
                -ms-transform: scale(3, 3);
                -webkit-transform: scale(3, 3);
                transform: scale(3, 3);
                opacity: 0;
            }

            50% {
                -ms-transform: scale(1, 1);
                -webkit-transform: scale(1, 1);
                transform: scale(1, 1);
                opacity: 1;
            }

            60% {
                -ms-transform: scale(1.1, 1.1);
                -webkit-transform: scale(1.1, 1.1);
                transform: scale(1.1, 1.1);
            }

            100% {
                -ms-transform: scale(1, 1);
                -webkit-transform: scale(1, 1);
                transform: scale(1, 1);
            }
        }

        @-webkit-keyframes fall-in {
            0% {
                -ms-transform: scale(3, 3);
                -webkit-transform: scale(3, 3);
                transform: scale(3, 3);
                opacity: 0;
            }

            50% {
                -ms-transform: scale(1, 1);
                -webkit-transform: scale(1, 1);
                transform: scale(1, 1);
                opacity: 1;
            }

            60% {
                -ms-transform: scale(1.1, 1.1);
                -webkit-transform: scale(1.1, 1.1);
                transform: scale(1.1, 1.1);
            }

            100% {
                -ms-transform: scale(1, 1);
                -webkit-transform: scale(1, 1);
                transform: scale(1, 1);
            }
        }

        @-o-keyframes fall-in {
            0% {
                -ms-transform: scale(3, 3);
                -webkit-transform: scale(3, 3);
                transform: scale(3, 3);
                opacity: 0;
            }

            50% {
                -ms-transform: scale(1, 1);
                -webkit-transform: scale(1, 1);
                transform: scale(1, 1);
                opacity: 1;
            }

            60% {
                -ms-transform: scale(1.1, 1.1);
                -webkit-transform: scale(1.1, 1.1);
                transform: scale(1.1, 1.1);
            }

            100% {
                -ms-transform: scale(1, 1);
                -webkit-transform: scale(1, 1);
                transform: scale(1, 1);
            }
        }

        @keyframes fall-in {
            0% {
                -ms-transform: scale(3, 3);
                -webkit-transform: scale(3, 3);
                transform: scale(3, 3);
                opacity: 0;
            }

            50% {
                -ms-transform: scale(1, 1);
                -webkit-transform: scale(1, 1);
                transform: scale(1, 1);
                opacity: 1;
            }

            60% {
                -ms-transform: scale(1.1, 1.1);
                -webkit-transform: scale(1.1, 1.1);
                transform: scale(1.1, 1.1);
            }

            100% {
                -ms-transform: scale(1, 1);
                -webkit-transform: scale(1, 1);
                transform: scale(1, 1);
            }
        }

        @-moz-keyframes plunge {
            0% {
                margin-top: -100%;
            }

            100% {
                margin-top: 15%;
            }
        }

        @-webkit-keyframes plunge {
            0% {
                margin-top: -100%;
            }

            100% {
                margin-top: 15%;
            }
        }

        @-o-keyframes plunge {
            0% {
                margin-top: -100%;
            }

            100% {
                margin-top: 15%;
            }
        }

        @keyframes plunge {
            0% {
                margin-top: -100%;
            }

            100% {
                margin-top: 15%;
            }
        }
    </style>
</head>

<body>
    <div class="background"></div>
    <div id="app">
        <div class="container">
            <!--/.row-->
            <?php if ($type == 'abort') : ?>
                <div class="row">
                    <div class="modalbox error col-sm-8 col-md-6 col-lg-5 center animate">
                        <div class="icon d-flex justify-content-center align-items-center">
                            <svg width="2.0625em" height="2em" viewBox="0 0 17 16" class="bi bi-exclamation-triangle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 5zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
                            </svg>
                        </div>
                        <!--/.icon-->
                        <h2><?php echo $status ?? 500; ?></h2>
                        <p><?php echo $message ?? 'ocorreu um erro inesperado'; ?></p>
                        <button type="button" class="redo btn">Tentar novamente</button>
                    </div>
                    <!--/.success-->
                </div>
            <?php else : ?>
                <div class="row">
                    <div class="modalbox error col-sm-8 col-md-6 col-lg-8 center animate">
                        <!--/.icon-->
                        <h2>Zacarias Error</h2>
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th scope="col">Mensagem</th>
                                    <th scope="col"><?php echo $message; ?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="row">Arquivo</th>
                                    <td><?php echo $file; ?></td>
                                </tr>
                                <tr>
                                    <th scope="row">Classe</th>
                                    <td><?php echo $class; ?></td>
                                </tr>
                                <tr>
                                    <th scope="row">Linha</th>
                                    <td><?php echo $line; ?></td>
                                </tr>
                            </tbody>
                        </table>

                        <h2>Código</h2>
                        <pre style="text-align: left;"><code class="php"><?php echo $file_code['code'] ?></code></pre>
                    </div>
                    <!--/.success-->
                </div>
            <?php endif; ?>
            <!--/.row-->
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function() {
            $('.redo').click(function() {
                return window.location.reload()
            });
        });

        document.addEventListener('DOMContentLoaded', (event) => {
            hljs.initLineNumbersOnLoad();
            document.querySelectorAll('pre code').forEach((block) => {
                hljs.highlightBlock(block);
                hljs.lineNumbersBlock(block);
            });

            setTimeout(() => {
                document.querySelectorAll('.hljs-ln tr')[<?php echo $file_code['error_line'] ?>].style.backgroundColor = "rgba(250, 99, 99, 0.3)"
                document.querySelector('.hljs-ln').style.width = '100%';
            }, 1000)
        });
    </script>
</body>

</html>
