<!-- Codificação caracteres da página -->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- SEO Geral -->
<title>Análise de Comportamento</title>
<meta name="description" content="Faça agora uma análise comportamental completa! Saiba qual o seu perfil comportamental. Descubra se você é lobo, tubarão, gato ou águia!">
<link rel="canonical" href="<?php echo $cofig['main']['url'] ?>">
<meta name="author" content="ReinanHS">
<meta name="robots" content="index">

<!-- Google+ / Schema.org -->
<meta itemprop="name" content="Análise comportamental - Teste de Perfil Comportamental - Prepara Cursos Simão Dias">
<meta itemprop="description" content="Faça agora uma análise comportamental completa! Saiba qual o seu perfil comportamental. Descubra se você é lobo, tubarão, gato ou águia!">
<meta itemprop="image" content="https://s3.amazonaws.com/ibc-portal/wp-content/uploads/2018/07/25152640/perfis-comportamentais.jpg">
<link href="https://plus.google.com/+SuaPagina" rel="publisher">

<!-- Open Graph Facebook -->
<meta property="og:title" content="Análise comportamental - Teste de Perfil Comportamental - Prepara Cursos Simão Dias">
<meta property="og:description" content="Faça agora uma análise comportamental completa! Saiba qual o seu perfil comportamental. Descubra se você é lobo, tubarão, gato ou águia!">
<meta property="og:site_name" content="Prepara Cursos Simão Dias - Análise comportamental"/>
<meta property="og:type" content="website">
<meta property="og:image" content="https://s3.amazonaws.com/ibc-portal/wp-content/uploads/2018/07/25152640/perfis-comportamentais.jpg">

<!-- Twitter -->
<meta name="twitter:title" content="Análise comportamental - Teste de Perfil Comportamental - Prepara Cursos Simão Dias">
<meta name="twitter:description" content="Faça agora uma análise comportamental completa! Saiba qual o seu perfil comportamental. Descubra se você é lobo, tubarão, gato ou águia!">
<meta name="twitter:url" content="<?php echo $cofig['main']['url'] ?>">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://s3.amazonaws.com/ibc-portal/wp-content/uploads/2018/07/25152640/perfis-comportamentais.jpg">
<!-- <meta name="twitter:creator" content="@estevanmaito"> -->
<meta name="twitter:site" content="@empresa">

<meta property="og:locale" content="pt_BR" />
<meta property="og:type" content="article" />
<meta property="og:title" content="Análise comportamental - Teste de Perfil Comportamental - Prepara Cursos Simão Dias" />
<meta property="og:description" content="Faça agora uma análise comportamental completa! Saiba qual o seu perfil comportamental. Descubra se você é lobo, tubarão, gato ou águia!" />
<meta property="og:url" content="<?php echo $cofig['main']['url'] ?>" />
<meta property="og:site_name" content="Portal" />
<meta property="article:section" content="Comportamento" />
<meta property="article:published_time" content="2018-12-17T12:00:49+00:00" />
<meta property="article:modified_time" content="2018-12-18T14:23:38+00:00" />
<meta property="og:updated_time" content="2018-12-17T14:23:38+00:00" />
<meta property="og:image" content="https://s3.amazonaws.com/ibc-portal/wp-content/uploads/2016/04/09211914/IBC-Instituto-Brasileiro-de-Coaching-Teste-Perfil-Comportamental.jpg" />
<meta property="og:image:secure_url" content="https://s3.amazonaws.com/ibc-portal/wp-content/uploads/2016/04/09211914/IBC-Instituto-Brasileiro-de-Coaching-Teste-Perfil-Comportamental.jpg" />
<meta property="og:image:width" content="720" />
<meta property="og:image:height" content="344" />
<meta property="og:image:alt" content="Perfil comportamental" />

<link rel="apple-touch-icon" sizes="57x57" href="<?php echo $cofig['main']['url'] ?>img/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="<?php echo $cofig['main']['url'] ?>img/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="<?php echo $cofig['main']['url'] ?>img/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="<?php echo $cofig['main']['url'] ?>img/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="<?php echo $cofig['main']['url'] ?>img/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="<?php echo $cofig['main']['url'] ?>img/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="<?php echo $cofig['main']['url'] ?>img/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="<?php echo $cofig['main']['url'] ?>img/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="<?php echo $cofig['main']['url'] ?>img/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="<?php echo $cofig['main']['url'] ?>img/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="<?php echo $cofig['main']['url'] ?>img/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="<?php echo $cofig['main']['url'] ?>img/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="<?php echo $cofig['main']['url'] ?>img/favicon-16x16.png">
<link rel="manifest" href="<?php echo $cofig['main']['url'] ?>img/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="<?php echo $cofig['main']['url'] ?>img/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">