<!DOCTYPE html>
<html lang="pt-br">
<head>
  <?php include_once($file.'view/home/meta_tags.phtml'); ?>
  <!-- Style -->
  <link rel="stylesheet" type="text/css" href="<?php echo $cofig['main']['url'] ?>css/result/style.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
	<section class="statistics">
		<h1>Resultados</h1>
		<ul>
		  <li class="chart" data-percent="<?php echo $quiz_i ?>">
		  	<span><?php echo $quiz_i ?>%</span>Águia
		  </li>
		  <li class="chart" data-percent="<?php echo $quiz_c ?>">
		  	<span><?php echo $quiz_c ?>%</span>Gato
		  </li>
		  <li class="chart" data-percent="<?php echo $quiz_a ?>">
		  	<span><?php echo $quiz_a ?>%</span>Tubarão
		  </li>
		  <li class="chart" data-percent="<?php echo $quiz_o ?>">
		  	<span><?php echo $quiz_o ?>%</span>Lobo
		  </li>
		</ul>
	</section>
	<div class="container">
		<div class="blog-post">
			<br><br><br>
            <h2 class="blog-post-title">O Poder do Teste de Perfil Comportamental!</h2>
            <p class="blog-post-meta">1º de janeiro de 2018 por <a href="https://www.ibccoaching.com.br/portal/comportamento/analise-comportamento-teste-perfil-comportamental/">Ibccoaching</a></p>

            <p>O Teste de Perfil Comportamental que, no Instituto Brasileiro de Coaching – IBC; chamamos de Coaching Assessment; é um instrumento poderoso de autoconhecimento e de autoavaliação do seu momento atual. Traz um questionário de rápido, objetivo e completo, uma vez que é feito por meio de perguntas diretas com múltiplas alternativas, e suas respostas ajudam a montar um mapeamento completo do seu perfil comportamental.</p>
            <p>O objetivo central da ferramenta é decifrar seu modelo mental, ou seja, ajudar a entender como você pensa e age, a <a href="https://www.ibccoaching.com.br/portal/lideranca-e-motivacao/realizar-dinamica-sobre-autoestima-motivacao/">fortalecer sua autoestima</a>, potencializar suas habilidades e diferenciais, destacar suas competências de liderança, minimizar ou eliminar os seus gaps e orientar seu potencial para melhores resultados.</p>
            <hr>
            <h2>O que é Analisado no Teste Comportamental?</h2>
            <p>Em essência, o teste comportamental é uma das metodologias mais assertivas e estratégicas no que tange a boa gestão de pessoas nas organizações. Ressalto isso porque é fato inegável que, quanto mais compatível for o seu quadro de funcionários com as suas necessidades, desafios e metas, maiores são suas chances de ser bem-sucedida.</p>
            <hr>
            <h3>Tubarão (Fazer Rápido)</h3>
            <p>Um dos bichos mais completos do reino animal, caçador-nato, figura no topo de sua cadeia alimentar. As pessoas com este perfil são consideradas mais focadas em resultados, determinadas, objetivas e capazes de superar seus desafios de forma precisa e rápida e com força e determinação.</p>
            <p>Quer saber mais sobre o perfil do Tubarão? Assista ao meu vídeo abaixo:</p>
            <center>
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/fAYyhfpdUEY" allowfullscreen></iframe>
                </div>
            </center>
            <br><h3>Gato (Fazer Junto)</h3>
            <p>O gato é um animal mitológico, pois conta-se que no antigo Egito era venerado tal qual um deus. Mesmo tendo seu próprio tempo, é também um bicho amoroso, brincalhão, carinhoso e acolhedor, um companheiro fiel.</p>
            <p>Não por acaso, os indivíduos com as características do perfil gato são consideradas mais receptivas, abertas ao trabalho em equipe e de fácil comunicação. Tem o poder de unir, ou seja, de aglutinar as pessoas ao seu redor, de gerar tranquilidade, harmonia e de pacificar os ambientes.</p>
            <p>Clique no vídeo abaixo para saber mais sobre o perfil comportamental do Gato:</p>
            <center>
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/Wap7ZuF9Yfg" allowfullscreen></iframe>
                </div>
            </center>
            <br><h3>Águia (Fazer Diferente)</h3>
            <p>Animal esplêndido, que voa alto e que, com sua visão privilegiada, consegue ver muito mais longe. Por isso, pessoas com as características da Águia são consideradas visionárias, criativas, capazes de visualizar o futuro e de provocar mudanças significativas ao seu redor. </p>
            <p>Confira o meu vídeo abaixo e saiba mais sobre os pontos fortes e de melhoria da Águia:</p>
            <center>
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/iWzFdTi2Huo" allowfullscreen></iframe>
                </div>
            </center>
            <br><h3>Lobo (Fazer Certo)</h3>
            <p>Animais meticulosos e observadores, cuja audição pode ser impactada pelo som de uma folha caindo, são fieis à sua matilha e por isso têm forte senso de grupo. Pessoas com o perfil “Lobo” são consideradas metódicas e organizadas, como também possuidoras de uma poderosa visão estratégica, o que lhes permite traçar planos simples ou complexos e colocá-los em prática com mais efetividade.</p>
            <p>Assista ao meu vídeo e conheça mais sobre as principais características do Lobo:</p>
            <center>
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/3P5lHApfrHc" allowfullscreen></iframe>
                </div>
            </center>
            <br><hr>
            <h3>Comentários:</h3>
            <div id="fb-root"></div>
			<script>(function(d, s, id) {
			  var js, fjs = d.getElementsByTagName(s)[0];
			  if (d.getElementById(id)) return;
			  js = d.createElement(s); js.id = id;
			  js.src = 'https://connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v3.2&appId=151605562091637&autoLogAppEvents=1';
			  fjs.parentNode.insertBefore(js, fjs);
			}(document, 'script', 'facebook-jssdk'));</script>
			<div class="fb-comments" data-href="<?php echo $cofig['main']['url'] ?>" data-numposts="10"></div>
          </div>
	</div><br>

	<footer class="blog-footer">
      <p>Esse site foi feito por <a href="http://reinanhs.github.io/">@ReinanHS</a></p>
      <p>
        <a href="#">De volta ao topo</a>
      </p>
    </footer>
  	<script type="text/javascript" src="<?php echo $cofig['main']['url'] ?>js/result/main.js"></script>
</body>
</html>