<!doctype html>

<html lang="pt-br">
<head>
  	<meta charset="utf-8">

	<title>Quiz</title>
  	<meta name="description" content="The HTML5 Herald">
  	<meta name="author" content="ReinanHS">

	<link rel="stylesheet" href="css/loading.css?v=1.0">
	<link rel="stylesheet" href="css/style.css?v=1.0">
	<link rel="stylesheet" href="https://unpkg.com/vue-toastr-2/dist/vue-toastr-2.min.css">

</head>

<body>

	<div id="app">
		<strat v-if="index == 0"></strat>
		<quiz v-if="index == 1"></quiz>
	</div>

	<?php include_once($file.'view/home/start.phtml'); ?>
	<?php include_once($file.'view/home/quiz.phtml'); ?>

	<script type="text/javascript">
		window.php_url = '<?php echo $cofig['main']['url']; ?>';
	</script>
	<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	<!-- <script src="js/main.js"></script> -->
	<!-- Vuejs -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue-resource@1.5.1"></script>
    <script src="https://unpkg.com/vue-toastr-2/dist/vue-toastr-2.js"></script>
	<script type="text/javascript">
		var strat = Vue.component('strat', {
			data: function () {
				return {
				  input_email: '',
				  index: 0,
				}
			},
			watch: {
				input_email : function(val){
				  app.config['email'] = val;
				},
			},
			methods:{
				next: function(){
					if(this.input_email.length < 8){
						this.$toastr.error('O campo email é obrigatorio', '', 
							{ 
								"positionClass": "toast-top-left",
								"progressBar": true,
								"closeButton": true, 
							}
						);
					}else if(this.index < 1){
						this.index++;
					}else if(this.index == 1){
						this.$toastr.info('Boa sorte', '', 
							{ 
								"positionClass": "toast-top-left",
								"closeButton": true, 
							}
						);

						app.index++;
					}
				},
			},
			template: '#start',
		});

		var quiz = Vue.component('quiz', {
			created: function(){
				this.getQuiz();
			},
			data: function () {
				return {
				  quiz_index: 1,
				  quiz: '',
				  quiz_a: '',
				  quiz_b: '',
				  quiz_c: '',
				  quiz_d: '',
				  load: false,
				}
			},
			methods:{
				quizNext: function(){
					this.load = false;
					this.getQuiz();		
				},
				getQuiz: function(){
					<?php if($cofig['main']['type'] == 'mysql'):?>
					var url = '<?php echo $cofig['main']['url']; ?>get/quiz/'+this.quiz_index;
					<?php else: ?>
					var url = '<?php echo $cofig['main']['url']; ?>js/json/'+this.quiz_index+'.json';
					<?php endif; ?>
					this.$http.get(url).then(response => {
						// success callback
						var data = JSON.parse(response.bodyText);
						this.quiz_index++;
						this.quiz = data['question'];
						this.quiz_a = data['i'];
						this.quiz_b = data['c'];
						this.quiz_c = data['o'];
						this.quiz_d = data['a'];

						this.load = true;
					}, response => {
						// error callback
					});
				},
				btn: function(elen){
					$(elen).parent().siblings(".answer").removeClass("active").children("span").remove();
					$(elen).parent().addClass("active").append("<span class='checkmark'>&#x2713;</span>");
				},
			},
		  	template: '#quiz',
		});

		var app = new Vue({
		  el: '#app',
		  data: {
		    index: 1,
		    config: {
		    	'email': '',
		    },
		  },
		  methods: {
		  }
		});
	</script>
</body>
</html>