<!doctype html>

<html lang="pt-br">
<head>
	<!-- Codificação caracteres da página -->
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- SEO Geral -->
	<title>Análise de Comportamento</title>
	<meta name="description" content="Faça agora uma análise comportamental completa! Saiba qual o seu perfil comportamental. Descubra se você é lobo, tubarão, gato ou águia!">
	<link rel="canonical" href="<?php echo $cofig['main']['url'] ?>">
	<meta name="author" content="ReinanHS">
	<meta name="robots" content="index">

	<!-- Google+ / Schema.org -->
	<meta itemprop="name" content="Análise comportamental - Teste de Perfil Comportamental - Prepara Cursos Simão Dias">
	<meta itemprop="description" content="Faça agora uma análise comportamental completa! Saiba qual o seu perfil comportamental. Descubra se você é lobo, tubarão, gato ou águia!">
	<meta itemprop="image" content="https://s3.amazonaws.com/ibc-portal/wp-content/uploads/2018/07/25152640/perfis-comportamentais.jpg">
	<link href="https://plus.google.com/+SuaPagina" rel="publisher">

	<!-- Open Graph Facebook -->
	<meta property="og:title" content="Análise comportamental - Teste de Perfil Comportamental - Prepara Cursos Simão Dias">
	<meta property="og:description" content="Faça agora uma análise comportamental completa! Saiba qual o seu perfil comportamental. Descubra se você é lobo, tubarão, gato ou águia!">
	<meta property="og:site_name" content="Prepara Cursos Simão Dias - Análise comportamental"/>
	<meta property="og:type" content="website">
	<meta property="og:image" content="https://s3.amazonaws.com/ibc-portal/wp-content/uploads/2018/07/25152640/perfis-comportamentais.jpg">

	<!-- Twitter -->
	<meta name="twitter:title" content="Análise comportamental - Teste de Perfil Comportamental - Prepara Cursos Simão Dias">
	<meta name="twitter:description" content="Faça agora uma análise comportamental completa! Saiba qual o seu perfil comportamental. Descubra se você é lobo, tubarão, gato ou águia!">
	<meta name="twitter:url" content="<?php echo $cofig['main']['url'] ?>">
	<meta name="twitter:card" content="summary">
	<meta name="twitter:image" content="https://s3.amazonaws.com/ibc-portal/wp-content/uploads/2018/07/25152640/perfis-comportamentais.jpg">
	<!-- <meta name="twitter:creator" content="@estevanmaito"> -->
	<meta name="twitter:site" content="@empresa">

	<meta property="og:locale" content="pt_BR" />
	<meta property="og:type" content="article" />
	<meta property="og:title" content="Análise comportamental - Teste de Perfil Comportamental - Prepara Cursos Simão Dias" />
	<meta property="og:description" content="Faça agora uma análise comportamental completa! Saiba qual o seu perfil comportamental. Descubra se você é lobo, tubarão, gato ou águia!" />
	<meta property="og:url" content="<?php echo $cofig['main']['url'] ?>" />
	<meta property="og:site_name" content="Portal" />
	<meta property="article:section" content="Comportamento" />
	<meta property="article:published_time" content="2018-12-17T12:00:49+00:00" />
	<meta property="article:modified_time" content="2018-12-18T14:23:38+00:00" />
	<meta property="og:updated_time" content="2018-12-17T14:23:38+00:00" />
	<meta property="og:image" content="https://s3.amazonaws.com/ibc-portal/wp-content/uploads/2016/04/09211914/IBC-Instituto-Brasileiro-de-Coaching-Teste-Perfil-Comportamental.jpg" />
	<meta property="og:image:secure_url" content="https://s3.amazonaws.com/ibc-portal/wp-content/uploads/2016/04/09211914/IBC-Instituto-Brasileiro-de-Coaching-Teste-Perfil-Comportamental.jpg" />
	<meta property="og:image:width" content="720" />
	<meta property="og:image:height" content="344" />
	<meta property="og:image:alt" content="Perfil comportamental" />

	<link rel="stylesheet" href="css/loading.css?v=1.0">
	<link rel="stylesheet" href="css/style.css?v=1.0">
	<link rel="stylesheet" href="https://unpkg.com/vue-toastr-2/dist/vue-toastr-2.min.css">

</head>

<body>

	<div id="app">
		<strat v-if="index == 0"></strat>
		<quiz v-if="index == 1"></quiz>
	</div>

	<?php include_once($file.'view/home/start.phtml'); ?>
	<?php include_once($file.'view/home/quiz.phtml'); ?>

	<script type="text/javascript">
		window.php_url = '<?php echo $cofig['main']['url']; ?>';
	</script>
	<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	<!-- <script src="js/main.js"></script> -->
	<!-- Vuejs -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue-resource@1.5.1"></script>
    <script src="https://unpkg.com/vue-toastr-2/dist/vue-toastr-2.js"></script>
	<script type="text/javascript">
		var strat = Vue.component('strat', {
			data: function () {
				return {
				  input_nome: '',
				  input_idade: '',
				  index: 0,
				}
			},
			watch: {
				input_nome : function(val){
				  app.config['nome'] = val;
				},
				input_idade : function(val){
				  app.config['idade'] = val;
				},
			},
			methods:{
				next: function(){
					if(this.input_nome.length < 8){
						this.$toastr.error('O campo nome é inválido deve ter 8 caracteres!', '', 
							{ 
								"positionClass": "toast-top-left",
								"progressBar": true,
								"closeButton": true, 
							}
						);
					}else if(this.input_idade.length < 0 || this.input_idade.length > 2){
						this.$toastr.error('O campo idade é inválido', '', 
							{ 
								"positionClass": "toast-top-left",
								"progressBar": true,
								"closeButton": true, 
							}
						);
					}else if(this.index < 1){
						this.index++;
					}else if(this.index == 1){
						this.$toastr.info('Boa sorte', '', 
							{ 
								"positionClass": "toast-top-left",
								"closeButton": true, 
							}
						);

						app.index++;
					}
				},
			},
			template: '#start',
		});

		var quiz = Vue.component('quiz', {
			created: function(){
				this.getQuiz();
			},
			data: function () {
				return {
				  quiz_index: 1,
				  quiz: '',
				  quiz_a: '',
				  quiz_b: '',
				  quiz_c: '',
				  quiz_d: '',
				  load: false,
				  result: [],
				  btn_next: false,
				}
			},
			methods:{
				quizNext: function(){
					if((this.quiz_index) < 26){
						if(this.btn_next){
							this.load = false;
							this.getQuiz();
							this.btn_next = false;
						}else{
							this.$toastr.error('Por favor selecione uma opção!', '', 
								{ 
									"positionClass": "toast-top-left",
									"closeButton": true, 
								}
							);
						}
							
					}else{
						this.quiz_index = 25;
						//app.index = 2;

						var quiz_a = 0;
						var quiz_b = 0;
						var quiz_c = 0;
						var quiz_d = 0;

						for (var i = this.result.length; i >= 0; i--) 
						{
							if(this.result[i] == 0){
								quiz_a++;
							}else if(this.result[i] == 1){
								quiz_b++;
							}else if(this.result[i] == 2){
								quiz_c++;
							}else if(this.result[i] == 3){
								quiz_d++;
							}
						}

						quiz_a = quiz_a * 4;
						quiz_b = quiz_b * 4;
						quiz_c = quiz_c * 4;
						quiz_d = quiz_d * 4;

						//app.result = dados;
						var url = '<?php echo $cofig['main']['url']; ?>set/result';

						var user = new FormData();
            			user.append('nome', app.config['nome']);
            			user.append('idade', app.config['idade']);
            			
            			user.append('i', quiz_a);
            			user.append('c', quiz_b);
            			user.append('o', quiz_c);
            			user.append('a', quiz_d);

            			this.$toastr.success('Aguarde alguns minutos', '', 
							{ 
								"positionClass": "toast-top-left",
								"closeButton": true, 
							}
						);
	
						this.$http.post(url, user).then(response => {
							// success callback
							window.location.href = "<?php echo $cofig['main']['url']; ?>"+"resultados";
							console.log(response);
						}, response => {
							// error callback
							this.$toastr.error('Ocorreu um erro por favor reinicie o navegador!', '', 
								{ 
									"positionClass": "toast-top-left",
									"closeButton": true, 
								}
							);
							console.log(response);
						});

						

					}	
				},
				getQuiz: function(){
					<?php if($cofig['main']['type'] == 'mysql'):?>
					var url = '<?php echo $cofig['main']['url']; ?>get/quiz/'+this.quiz_index;
					<?php else: ?>
					var url = '<?php echo $cofig['main']['url']; ?>js/json/'+this.quiz_index+'.json';
					<?php endif; ?>
					this.$http.get(url).then(response => {
						// success callback
						var data = JSON.parse(response.bodyText);
						this.quiz_index++;
						this.quiz = data['question'];
						this.quiz_a = data['i'];
						this.quiz_b = data['c'];
						this.quiz_c = data['o'];
						this.quiz_d = data['a'];

						this.load = true;
					}, response => {
						// error callback
					});
				},
				btn: function(elen, index){
					this.btn_next = true;

					var lista = document.querySelectorAll('li.box');

					for (var i = 0; i < lista.length; i++) 
					{
						$(lista[i]).removeClass("active").children("span").remove();
					}

					$(lista[index]).addClass("active").append("<span class='checkmark'>&#x2713;</span>");

					this.result[this.quiz_index-1] = index;
				},
			},
		  	template: '#quiz',
		});

		var app = new Vue({
		  el: '#app',
		  data: {
		    index: 0,
		    result: [],
		    config: {
		    	'nome': '',
		    	'idade': '',
		    },
		  },
		  methods: {
		  }
		});
	</script>
</body>
</html>